list.h
aos_offsetof
aos_container_of
dlist_entry
AOS_DLIST_INIT
dlist_first_entry
dlist_for_each
dlist_for_each_safe
dlist_for_each_entry
dlist_for_each_entry_safe
list_entry
dlist_for_each_entry_reverse
dlist_entry_number
AOS_DLIST_HEAD_INIT
AOS_DLIST_HEAD
slist_for_each_entry
slist_for_each_entry_safe
AOS_SLIST_HEAD_INIT
AOS_SLIST_HEAD
slist_entry
slist_first_entry
slist_entry_number
typedef struct dlist_s dlist_t
typedef struct slist_s slist_t
static void __dlist_add(dlist_t *node, dlist_t *prev, dlist_t *next)
References dlist_s::next, dlist_s::prev.
Referenced by dlist_add, dlist_add_tail.
static void dlist_add(dlist_t *node, dlist_t *queue)
References __dlist_add, dlist_s::next.
static void dlist_add_tail(dlist_t *node, dlist_t *queue)
References __dlist_add, dlist_s::prev.
static void dlist_del(dlist_t *node)
References dlist_s::next, dlist_s::prev.
static void dlist_init(dlist_t *node)
References dlist_s::next, dlist_s::prev.
static void INIT_AOS_DLIST_HEAD(dlist_t *list)
References dlist_s::next, dlist_s::prev.
static int dlist_empty(const dlist_t *head)
References dlist_s::next.
static void slist_add(slist_t *node, slist_t *head)
References slist_s::next.
Referenced by slist_add_tail.
static void slist_add_tail(slist_t *node, slist_t *head)
References slist_s::next, slist_add.
static void slist_del(slist_t *node, slist_t *head)
References slist_s::next.
static int slist_empty(const slist_t *head)
References slist_s::next.
static void slist_init(slist_t *head)
References slist_s::next.